const assert=require('node:assert/strict');
const fs=require('node:fs');
const core=require('../dist/price-core.js');
const full=JSON.parse(fs.readFileSync(process.argv[2]||'tests/fixtures/reference-types-20260904.json','utf8'));
core.validateSnapshot(full);
const sample={...full,items:full.items.filter(r=>[1913,15758].includes(r.complex_id))};
const filters={q:'',districts:null,areaMin:24,areaMax:32,households:0,budget:150000,budgetOnly:true};
const get=(cid,aid)=>sample.items.find(r=>r.complex_id===cid&&r.area_id===aid);
const swanSmall=get(1913,1801),swan30=get(1913,171537),samsungSmall=get(15758,15498),samsung33=get(15758,134592);
assert.equal(swanSmall.supply_pyeong,13.46);assert.equal(swanSmall.general_price_manwon,66000);
assert.equal(swan30.supply_pyeong,30.85);assert.equal(swan30.general_price_manwon,162000);
assert.equal(samsungSmall.supply_pyeong,12.52);assert.equal(samsungSmall.general_price_manwon,127500);
assert.equal(samsung33.supply_pyeong,33.09);assert.equal(samsung33.general_price_manwon,350000);
assert.equal(sample.items.filter(r=>core.matches(r,filters)).length,0,'24–32평 + 15억 이하: 두 단지 모두 제외');
const rangeOnly={...filters,budgetOnly:false};
assert.deepEqual(sample.items.filter(r=>core.matches(r,rangeOnly)).map(r=>r.area_id).sort((a,b)=>a-b),[51105,94742,171537].sort((a,b)=>a-b));
const edge={...swan30,supply_pyeong:32,general_price_manwon:150000};
assert(core.matches(edge,filters));
assert(!core.matches({...edge,supply_pyeong:32.01},filters));
assert(!core.matches({...edge,supply_pyeong:23.99},filters));
assert(!core.matches({...edge,general_price_manwon:150001},filters));
assert(!core.matches({...edge,general_price_manwon:null,price_status:'unavailable'},filters));
assert(core.matches(samsung33,{...rangeOnly,areaMin:33,areaMax:34}));
assert(core.matches(samsungSmall,{...rangeOnly,areaMin:null,areaMax:null}));
assert(!core.matches(swan30,{...rangeOnly,districts:new Set(['강남구','서초구'])}));
assert(core.matches(swan30,{...rangeOnly,districts:new Set(['강남구','송파구'])}));
assert(!core.matches(swan30,{...rangeOnly,districts:new Set()}));
for(const direction of ['asc','desc']) {
 const sorted=[{...swan30,general_price_manwon:null},samsung33,swanSmall].sort((a,b)=>core.compareRows(a,b,{key:'price',direction},150000));
 assert.equal(sorted[2].general_price_manwon,null);
 assert.equal(sorted[0].general_price_manwon,direction==='asc'?66000:350000);
}
assert.throws(()=>core.validateSnapshot({schema_version:1,items:[]}));
assert.throws(()=>core.validateSnapshot({...sample,type_count:sample.type_count+1}));
assert.throws(()=>core.validateSnapshot({...sample,items:[swan30,swan30],type_count:2}));
assert.throws(()=>core.validateSnapshot({...sample,items:[{...swan30,price_status:'ai_excluded'}],type_count:1}));
assert.throws(()=>core.validateSnapshot({...full,errors:[{complex_id:1,error:'failure'}]}));
assert.throws(()=>core.validateSnapshot({...full,successful_complex_count:full.target_complex_count-1}));
const csv=core.toCSV([swan30]);assert(csv.includes('"30.85"'));assert(csv.includes('"162000"'));assert(!csv.includes('66000'));
assert(core.toCSV([{...swan30,name:'=formula,"test"'}]).includes('"\'=formula,""test"""'));
console.log('PASS: exact type identity, price mapping, numeric bounds, budgets, districts, null sorting, CSV, schema guards');
const variants=[0,1,2,3].map((n)=>({...swan30,area_id:n+1,supply_pyeong:30+n,exclusive_pyeong:24+n,general_price_manwon:149000+n*1000}));
const untouched=JSON.stringify(variants),groups=core.groupSimilar(variants,2);
assert.deepEqual(groups.map(g=>g.members.length),[3,1]);
assert.equal(JSON.stringify(variants),untouched,'grouping preserves original records');
assert.equal(groups[0].general_price_manwon,149000);
assert.equal(core.groupSimilar(variants,1).length,2);
assert.equal(core.groupSimilar([variants[0],{...variants[1],complex_id:999}],2).length,2);
assert.equal(core.groupSimilar([variants[0],{...variants[1],exclusive_pyeong:28}],2).length,2);
assert.equal(core.groupSimilar([variants[0],{...variants[1],exclusive_pyeong:null}],2).length,2);
assert.deepEqual(core.groupSimilar(variants.filter(r=>core.matches(r,filters)),2).flatMap(g=>g.members).map(r=>r.area_id),[1,2]);
console.log('PASS: bounded grouping, missing areas, complex separation, immutable records and filter boundaries');
