create table if not exists public.manual_refresh_requests (
  id bigint generated by default as identity primary key,
  requested_at timestamptz not null default now(),
  source text not null default 'dashboard'
);

alter table public.manual_refresh_requests enable row level security;

revoke all on table public.manual_refresh_requests from anon, authenticated;
revoke all on sequence public.manual_refresh_requests_id_seq from anon, authenticated;

create index if not exists manual_refresh_requests_requested_at_idx
  on public.manual_refresh_requests (requested_at desc);
